/**
 * Created by Ever on 15/06/2017.
 * updated on 29/06/2017
 */
/*
*@FEATURE TestCoverage: <A short but clear description of the feature being tested, it's a best practice to include the related issue number (#issueId)>
*/
@IsTest
private class TestCI_Test {
    /*
    *Setup required data for all test methods.
    */
    @TestSetup
    static void setup() {

    }   
    /*
 	* @SCENARIO TestAll: <Explanation of the scenario goes here>
	*/
    static testMethod void testBehavior() {
        /*
        * @GIVEN <a set of initial conditions.>
        */
        
        /*
        * @AND <more initial conditions>
        */
        
        /*
        * @WHEN <some action is fired by the actor>
        */
        
        /*
        * @THEN <a testeable output should be generated>
        */
        
        /*
        * @AND <any other output variables>
        */
        
        /*
        * @AND <more output variables>
        */
    }
}
